FROM aursu/rpmbuild:7-build

USER root
RUN yum -y install \
        cmake \
        libcurl-devel \
        multilib-rpm-config \
        openssl-devel \
    && yum clean all && rm -rf /var/cache/yum

# RUN yum -y --enablerepo=bintray-custom install \
#    && yum clean all && rm -rf /var/cache/yum
